# Generated by Django 3.2.12 on 2022-04-09 17:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tasks',
            name='due_date',
        ),
    ]
