# Generated by Django 3.2.12 on 2022-04-09 18:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_remove_tasks_due_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tasks',
            name='creation_date',
        ),
    ]
