# Generated by Django 3.2.12 on 2022-04-11 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_tasks_creation_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='tasks',
            name='update_date',
            field=models.DateField(auto_now=True),
        ),
    ]
