# Generated by Django 3.2.12 on 2022-04-11 12:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_tasks_update_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tasks',
            name='update_date',
        ),
    ]
